from .Contact import *
from .Orders import *
from .ProductPrice import *
from .Products import *
from .Restaurant import *
from .Waiters import *
from .RestaurantLocations import *
from .Tax import *
from .Menu import *
