# Generated by Django 5.1.6 on 2025-02-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='contact',
            new_name='owner',
        ),
    ]
