# Generated by Django 5.1.6 on 2025-02-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0002_rename_contact_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
