# Generated by Django 5.1.6 on 2025-02-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0003_productcategory_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprice',
            old_name='date',
            new_name='created_on',
        ),
    ]
