# Generated by Django 5.1.6 on 2025-02-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0004_rename_date_productprice_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
