# Generated by Django 5.1.6 on 2025-02-09 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0005_alter_productprice_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapi.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapi.productcategory')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurantapi.menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='restaurantapi.menu')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurantapi.productprice')),
            ],
        ),
    ]
