# Generated by Django 5.1.6 on 2025-05-14 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0009_alter_orders_waiter_userprofile_active_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='item_name',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderDetails_set', to='restaurantapi.product'),
            preserve_default=False,
        ),
    ]
