# Generated by Django 5.1.6 on 2025-05-21 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0010_remove_orderdetails_item_name_orderdetails_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurantapi.restaurantlocations'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurantapi.restaurant'),
        ),
    ]
