# Generated by Django 5.1.6 on 2025-05-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0011_alter_orders_location_alter_orders_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='mandatory',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='restaurantapi.restaurant'),
        ),
    ]
