# Generated by Django 5.1.6 on 2025-05-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0012_tax_mandatory_tax_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
