# Generated by Django 5.1.6 on 2025-07-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0015_alter_ordertaxes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='reserved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
